sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: XJnLuiSZq3AxqQEam00/bzVHq3Zso73+2qNpit1hsPL7GQe/srLXP15WYqNkBHGTCxEcJpMeD/bLPM0KbhwglZDw3uOO+YfWl+mqRpKaaGZZAbXaE2R6oVtJhc5Gy9Zi+zkjQKL+cT3BSWb4QSLi+mlEwnqttKBxkojF+OfUoRd9wIbIzVOsY6v/nhwV7wrfy2KlupS+LwassL4QsT3/5TKuB1b289die5ZyUyVn1eoFtHVdatq+TgWDMcJu9bXLzwyoZz5EQdttfBkzlM6lDBeJV7hRbmVxbjkVzdUCa63Q7Bjb+YWVXBkNALpLPW+iju0yt1IUBCtJyGISDB65TXTTL3UMEQYKP/wnDaLFlALVSh1xSiXTpsdzWhY582jXbZf5LVOY2E9p9d2yPr6LPwWr5e78MkMcYxR21h0nQ7fi41UHTWBo1/cZcaFplPTk0jdRquFxDm98MVWXMFM8ecvNBhfAeWIRHs2RDBYOqkHFgeNZOv6FEOrvnRWtz70gSApUXxWXbN6Exd7wNl1AnJFw5m4WCnjcFuyCFur9KsdUywuA/+88EEbFjSK1iSoOmfZnYrTjm+LoctLV1e48tGYK+MfQ+nPYVyPh7I8fvNxsh+j9H4zBU/ytCm6D3n+RObGe2ru3IMNsq3muh7r0p/TL1ZwXFXi5u8wcM67fR28=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/A-Woman-of-No-Importance_854
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy